// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtzrgpfajsomexbojtxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0enJncGZhanNvbWV4Ym9qdHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjQyNzAsImV4cCI6MjA3MjA0MDI3MH0.ksMFaniK6SVcTaavkL5viIOoX-DB1BLwuguxVOf-Uhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});